article/urls.py
from django.conf.urls import url
from . import views
from . import list_views

urlpatterns = [
    url(r'^article_column/$', views.article_column, name="article_column"),
    url(r'^rename_article_column/$', views.rename_article_column, name="rename_article_column"),
    url(r'^delete_article_column/$', views.delete_article_column, name="delete_article_column"),
    url(r'^article_post/$', views.article_post, name="article_post"),
    url(r'^article_list/$', views.article_list, name="article_list"),
    url(r'^article_detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.article_detail, name="article_detail"),
    url(r'^delete_article/$', views.delete_article, name="delete_article"),
    url(r'^redit_article/(?P<article_id>[-\w]+)/$', views.redit_article, name="redit_article"),
    url(r'^list_article_titles/$', list_views.article_titles, name="list_article_titles"),
    url(r'^list_article_titles/(?P<username>[-\w]+)/$', list_views.article_titles, name="author_articles"),
    url(r'^list_article_detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', list_views.article_detail, name="list_article_detail"),
    url(r'^like_article/$', list_views.like_article, name="like_article"),
    url(r'^article_tag/$', views.article_tag, name="article_tag"),
    url(r'^del_article_tag/$', views.del_article_tag, name="del_article_tag"),
]
app_name = 'article'

blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.blog_title, name='blog_title'),
    url(r'(?P<article_id>\d)/$', views.blog_article, name="blog_detail")
]
app_name = 'blog'

demo/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^pwd_reset/', include('password_reset.urls'), name='pwd_reset'),
    url(r'^article/', include('article.urls'), name='article'),
    url(r'^image/', include('image.urls'), name='image'),
    url(r'^course/', include('course.urls'), name='course'),
    url(r'^home/', TemplateView.as_view(template_name="home.html")),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/models.py
from django.db import models
from django.contrib.auth.models import User
from slugify import slugify
from django.utils import timezone
from django.urls import reverse


# Create your models here.
class ArticleColumn(models.Model):
    user = models.ForeignKey(User, related_name='article_column', on_delete=models.CASCADE)
    column = models.CharField(max_length=200)
    created = models.DateField(auto_created=True)

    def __str__(self):
        return self.column


class ArticleTag(models.Model):
    author = models.ForeignKey(User, related_name='tag',on_delete=models.CASCADE)
    tag = models.CharField(max_length=500)

    def __str__(self):
        return self.tag


class ArticlePost(models.Model):
    author = models.ForeignKey(User, related_name="article", on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=500)
    column = models.ForeignKey(ArticleColumn, related_name='article_column', on_delete=models.CASCADE)
    body = models.TextField()
    created = models.DateTimeField(default=timezone.now())
    updated = models.DateTimeField(auto_now=True)
    user_like = models.ManyToManyField(User, related_name='article_like', blank=True)
    article_tag = models.ManyToManyField(ArticleTag, related_name='article_tag')

    class Meta:
        ordering = ('title',)
        index_together = (('id', 'slug'),)  # 对这两个字段建立索引

    def __str__(self):
        return self.title

    def save(self, *args, **kargs):
        self.slug = slugify(self.title)
        super(ArticlePost, self).save(*args, **kargs)

    def get_absolute_url(self):
        return reverse('article:article_detail', args=[self.id, self.slug])

    def get_url_path(self):
        return reverse('article:list_article_detail', args=[self.id, self.slug])


class Comment(models.Model):
    article = models.ForeignKey(ArticlePost, related_name='comments', on_delete=models.CASCADE)
    commentator = models.CharField(max_length=90)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ("-created",)

    def __str__(self):
        return "Comment by {0} on {1}".format(self.commentator.username, self.article)

article/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import ArticleColumn, ArticlePost, ArticleTag
from .form import ArticleColumnForm, ArticlePostForm, ArticleTagForm
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import json


# Create your views here.

@login_required(login_url='/account/login/')
@csrf_exempt
def article_column(request):
    if request.method == "GET":
        columns = ArticleColumn.objects.filter(user=request.user)  # 根据当前用户筛选出和当前用户一直的文章的元组
        column_form = ArticleColumnForm()
        return render(request, 'article/column/article_column.html', {"columns": columns, "column_form": column_form})
    if request.method == "POST":
        column_name = request.POST['column']
        columns = ArticleColumn.objects.filter(user_id=request.user.id, column=column_name)
        if columns:
            return HttpResponse('2')
        else:
            ArticleColumn.objects.create(user=request.user, column=column_name)
            return HttpResponse('1')


@login_required(login_url='/account/login/')
@csrf_exempt
def rename_article_column(request):
    column_name = request.POST['column_name']
    column_id = request.POST['column_id']
    try:
        line = ArticleColumn.objects.get(id=column_id)
        line.column = column_name
        line.save()
        return HttpResponse('1')
    except:
        return HttpResponse('0')


@login_required(login_url='/account/login/')
@csrf_exempt
def delete_article_column(request):
    column_id = request.POST['column_id']
    try:
        line = ArticleColumn.objects.get(id=column_id)
        line.delete()
        return HttpResponse('1')
    except:
        return HttpResponse('0')


@login_required(login_url='/account/login/')
@csrf_exempt
def article_post(request):
    if request.method == "POST":
        article_post_form = ArticlePostForm(data=request.POST)  # 获取表单数据
        if article_post_form.is_valid():
            cd = article_post_form.cleaned_data
            try:
                new_article = article_post_form.save(commit=False)  # 将表单对象转换成实体对象，暂时不提交数据库
                new_article.author = request.user  # 将当前用户对象赋值给实体对象
                new_article.column = request.user.article_column.get(
                    id=request.POST['column_id'])  # 通过外键将column对象赋值给实体对象
                new_article.save()
                tags = request.POST['tags']
                print(tags)
                if tags:
                    for tag in json.loads(tags):
                        tag = request.user.tag.get(tag=tag)
                        new_article.article_tag.add(tag)
                return HttpResponse('1')
            except:
                return HttpResponse('2')
        else:
            return HttpResponse('3')
    else:
        article_post_form = ArticlePostForm()
        article_tags = request.user.tag.all()
        article_columns = request.user.article_column.all()
        return render(request, "article/column/article_post.html",
                      {"article_post_form": article_post_form, "article_columns": article_columns,
                       "article_tags": article_tags})


@login_required(login_url='/account/login/')
@csrf_exempt
def article_list(request):
    articles_list = ArticlePost.objects.filter(author=request.user)
    paginator = Paginator(articles_list, 4)
    page = request.GET.get('page')
    try:
        current_page = paginator.page(page)
        articles = current_page.object_list
    except PageNotAnInteger:
        current_page = Paginator.page(self=paginator, number=1)
        articles = current_page.object_list
    except EmptyPage:
        current_page = paginator.page(paginator.num_pages)
        articles = current_page.object_list
    return render(request, "article/column/article_list.html", {"articles": articles, "page": current_page})


@login_required(login_url='/account/login/')
@csrf_exempt
def article_detail(request, id, slug):
    article = get_object_or_404(ArticlePost, id=id, slug=slug)
    return render(request, "article/column/article_detail.html", {"article": article})


@login_required(login_url='/account/login/')
@csrf_exempt
def delete_article(request):
    article_id = request.POST['article_id']
    try:
        line = ArticlePost.objects.get(id=article_id)
        line.delete()
        return HttpResponse('1')
    except:
        return HttpResponse('0')


@login_required(login_url='/account/login/')
@csrf_exempt
def redit_article(request, article_id):
    if request.method == "GET":
        article_columns = request.user.article_column.all()  # 获取当前用户的所有columns
        article = ArticlePost.objects.get(id=article_id)  # 获取当前需要修改的article
        this_article_form = ArticlePostForm(initial={"title": article.title})  # 获取当前获取当前需要修改的article主题的input对象
        this_article_column = article.column  # 获取column的input对象
        return render(request, 'article/column/redit_article.html',
                      {"article": article, "article_columns": article_columns, "this_article_form": this_article_form,
                       "this_article_column": this_article_column})
    else:
        redit_article = ArticlePost.objects.get(id=article_id)
        try:
            redit_article.column = request.user.article_column.get(id=request.POST['column_id'])
            redit_article.title = request.POST['title']
            redit_article.body = request.POST['body']
            redit_article.save()
            return HttpResponse('1')
        except:
            return HttpResponse('2')


@login_required(login_url='/account/login/')
@csrf_exempt
def article_tag(request):
    if request.method == "GET":
        article_tag = ArticleTag.objects.filter(author=request.user)
        article_tag_form = ArticleTagForm()
        return render(request, 'article/tag/tag_list.html',
                      {"article_tag_form": article_tag_form, "article_tag": article_tag})
    if request.method == "POST":
        article_tag_form = ArticleTagForm(data=request.POST)
        if article_tag_form.is_valid():
            try:
                new_tag = article_tag_form.save(commit=False)
                new_tag.author = request.user
                new_tag.save()
                return HttpResponse('1')
            except:
                return HttpResponse('the data cannot be save')
        else:
            return HttpResponse('sorry,the form is not valid')


@login_required(login_url='/account/login/')
@csrf_exempt
def del_article_tag(request):
    tag_id = request.POST['id']
    try:
        article_tag = ArticleTag.objects.filter(id=tag_id)
        article_tag.delete()
        return HttpResponse('1')
    except:
        return HttpResponse('2')

templates/article/column/article_column.html
{% extends 'article/base.html' %}
{% load staticfiles %}
{% block title %}article column{% endblock %}
{% block js %}
    <script type="text/javascript">
        function add_column() {
            var index = layer.open({
                type: 1,
                skin: "layui-layer-rim",
                area: ['400px', '200px'],
                title: '新增栏目',
                content: "<div class='text-center' style='margin-top:20px'><p>请输入新的栏目名称</p><p>{{ column_form.column }}</p></div>",
                btn: ['确定', '取消'],
                yes: function (index, layero) {//index即代表当前弹出框的对象，layero即对象本身
                    column_name = $('#id_column').val();//获取弹出框中输入的值，也就是content中的input框中的值
                    $.post('{% url "article:article_column" %}', {"column": column_name}, function (data) {
                        if (data == '1') {//根据返回值判断是否输入的值已存在数据库中
                            parent.location.reload();//不存在就重新加载当前页的上一页
                            layer.msg('good');
                        } else {
                            layer.msg('此栏目已有，请更换名称');//存在就提示
                        }
                    });
                },
                btn2: function (index, layero) {
                    layer.close(index);
                }
            });
        }
    </script>
    <script type="text/javascript">
        function edit_column(the, id) {
            var name = $(the).parent('tr').children('td').eq(1).text();
            var index = layer.open({
                type: 1,
                skin: "layui-layer-rim",
                area: ["400px,200px"],
                title: '编辑栏目',
                content: "<div class='text-center' style='margin-top:20px'><p>请输入新的栏目名称</p><p><input type='text' id='new_name' value=''+name+''></p></div>",
                btn: ['确定', '取消'],
                yes: function (index, layero) {
                    new_name = $('#new_name').val();
                    $.post('{% url "article:rename_article_column" %}', {
                        "column_id": id,
                        'column_name': column_name
                    }, function (data) {
                        if (data == "1") {
                            parent.location.reload();
                            layer.msg("good");
                        } else {
                            layer.msg("新的名称不可用");
                        }
                    });
                }
            })
        }
    </script>
    <script type="text/javascript">
        function del_column(the, id) {
            var name = $(the).parent('tr').children('td').eq(1).text();
            var index = layer.open({
                type: 1,
                skin: "layui-layer-rim",
                area: ["400px,200px"],
                title: '删除栏目',
                content: "<div class='text-center' style='margin-top:20px'><p>确定删除</p></div>",
                btn: ['确定', '取消'],
                yes: function (index, layero) {
                    $.post('{% url "article:delete_article_column" %}', {
                        "column_id": id
                    }, function (data) {
                        if (data == "1") {
                            parent.location.reload()
                            layer.msg("good")
                        } else {
                            layer.msg("删除失败")
                        }
                    });
                }
            })
        }
    </script>
{% endblock %}
{% block content %}
    <div>
        <p class="text-right">
            <button class=" btn btn-primary btn-lg" onclick="add_column()" id="add_column">add column</button>
        </p>
        <table class="table table-hover">
            <tr>
                <td>序号</td>
                <td>栏目名称</td>
                <td>操作</td>
            </tr>
            {% for column in columns %}
                <tr>
                    <td>{{ forloop.counter }}</td><!--获取当前循环的序号-->
                    <td>{{ column.column }}</td>
                    <td>
                        <a name="edit" href="javascript:void(0)" onclick="edit_column(this,{{ column.id }})">
                            <span class="glyphicon glyphicon-pencil"></span>
                        </a>
                        <a name="delete" href="javascript:void(0)" onclick="del_column(this,{{ column.id }})">
                            <span class="glyphicon glyphicon-trash" style="margin-left: 20px"></span>
                        </a>
                    </td>
                </tr>
            {% empty %}
                <p>还没设置栏目，太懒了</p><!--循环为空就显示当前内容,empty省略if判断-->
            {% endfor %}
        </table>
    </div>

{% endblock %}

templates/article/column/article_list.html
{% extends 'article/base.html' %}
{% load staticfiles %}
{% block title %}article list{% endblock %}
{% block js %}
    <script type="text/javascript">
        function del_article(the, id) {
            layer.open({
                type: 1,
                skin: "layui-layer-rim",
                area: ["400px", "200px"],
                title: "删除文章",
                btn: ["确定", "取消"],
                content: "<div class='text-center' style='margin-top:20px'><p>确定删除</p></div>",
                yes: function () {
                    $.post("{% url 'article:delete_article' %}", {"article_id": id}, function (data) {
                        if (data == "1") {
                            parent.location.reload();
                            layer.msg("successful");
                        } else {
                            layer.msg("删除失败");
                        }
                    });
                }
            });
        }
    </script>
{% endblock %}
{% block content %}
    <div>
        <table class="table table-hover">
            <tr>
                <td>序号</td>
                <td>标题</td>
                <td>栏目</td>
                <td>操作</td>
            </tr>
            {% for article in articles %}
                <tr id="{{ article.id }}">
                    <td>{{ forloop.counter }}</td>
                    <td><a href="{{ article.get_absolute_url }}">{{ article.title }}</a></td>
                    <td>{{ article.column }}</td>
                    <td>
                        <a name="editor" href="{% url 'article:redit_article' article.id %}">
                            <span class="glyphicon glyphicon-pencil"></span>
                        </a>
                        <a name="delete" href="javascript:void(0)" onclick="del_article(this,{{ article.id }})">
                            <span class="glyphicon glyphicon-trash" style="margin-left: 20px"></span>
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </table>
        {% include 'article/paginator.html' %}
    </div>
{% endblock %}

templates/article/column/article_post.html
{% extends 'article/base.html' %}
{% load staticfiles %}
{% block title %}article column{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'editor/css/editormd.css' %}"/>
    <link rel="stylesheet" href="{% static 'editor/css/style.css' %}"/>
{% endblock %}
{% block js %}
    <script type="text/javascript" src="{% static 'editor/editormd.amd.min.js' %}"></script>
    <script type="text/javascript">
        $(function () {
            var editor = editormd("editormd", {
                width: "100%",
                height: 640,
                syncScrolling: "single",
                path: "{% static 'editor/lib/' %}"
            });
        });
    </script>
{% endblock %}
{% block content %}
    <form class="form-horizontal" action="." method="post">{% csrf_token %}
        <div class="row" style="margin-top: 10px">
            <div class="col-md-2 text-right"><span>标题</span></div>
            <div class="col-md-10 text-left">{{ article_post_form.title }}</div>
        </div>
        <div class="row" style="margin-top: 10px">
            <div class="col-md-2 text-right"><span>栏目</span></div>
            <div class="col-md-10 text-left">
                <select id="which_column">
                    {% for column in article_columns %}
                        <option value="{{ column.id }}">{{ column.column }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="row" style="margin-top: 10px">
            <div class="col-md-2 text-right"><span>文章标签</span></div>
            <div class="col-md-10 text-left">
                {% for tag in article_tags %}
                    <label class="checkbox-inline">
                        <input class="tagcheckbox" type="checkbox" id="{{ tag.id }}" name="article_tag"
                               value="{{ tag.tag }}">{{ tag.tag }}
                    </label>
                {% empty %}
                    <p>You have not type tags for articles ,Please <a href="{% url 'article:article_tag' %}">input your
                        tags</a></p>
                {% endfor %}
            </div>
        </div>
        <div class="row" style="margin-top: 10px">
            <div class="col-md-2 text-right"><span>内容</span></div>

            <div id="editormd" class="col-md-10 text-left">
                <textarea style="display: none" id="id_body"></textarea>
            </div>
        </div>
        <div class="row">
            <input type="button" class="btn btn-primary btn-lg" value="发布" onclick="publish_article()">
        </div>
    </form>
    <script type="text/javascript">
        function publish_article() {
            var title = $('#id_title').val();
            var column_id = $('#which_column').val();
            var body = $('#id_body').val();
            var article_tags = [];
            $.each($("input[name='article_tag']:checked"), function () {
                article_tags.push($(this).val());
            });
            $.post("{% url 'article:article_post' %}", {
                "title": title,
                "column_id": column_id,
                "body": body,
                'tags': JSON.stringify(article_tags)
            }, function (data) {
                if (data == "1") {
                    layer.msg("successful");
                    location.href = "{% url 'article:article_list' %}";
                } else if (data == "2") {
                    layer.msg("sorry");
                } else {
                    layer.msg("项目名称不能为空")
                }
            })
        }
    </script>
{% endblock %}

templates/article/column/redit_article.html
{% extends 'article/base.html' %}
{% load staticfiles %}
{% block title %}article column{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'editor/css/style.css' %}"/>
    <link rel="stylesheet" href="{% static 'editor/css/editormd.css' %}"/>
{% endblock %}
{% block js %}
    <script type="text/javascript" src="{% static 'editor/editormd.js' %}"></script>
    <script type="text/javascript">
        $(function () {
            var editor = editormd('editormd', {
                width: "100%",
                height: 640,
                path: "{% static 'editor/lib/' %}",
            });
        })


    </script>
    <script type="text/javascript">
        function redit_article() {
            var title = $('#id_title').val();
            var column_id = $('#which_column').val();
            var body = $('#id_body').val();
            $.post("{% url 'article:redit_article' article.id %}", {
                "title": title,
                "column_id": column_id,
                "body": body
            }, function (data) {
                if (data == "1") {
                    layer.msg("successful");
                    location.href = "{% url 'article:article_list' %}";
                } else {
                    layer.msg("sorry");
                }
            });
        }
    </script>
{% endblock %}
{% block content %}
    <div class="container">
        <div class="col-md-10">
            <div style="margin-left: 10px">
                <form class="form-horizontal" action="." method="post">{% csrf_token %}
                    <div class="row" style="margin-top: 10px">
                        <div class="col-md-2 text-right"><span>标题：</span></div>
                        <div class="col-md-10 text-left">{{ this_article_form.title }}</div>
                    </div>
                    <div class="row" style="margin-top: 10px">
                        <div class="col-md-2 text-right"><span>栏目：</span></div>
                        <div class="col-md-10 text-left">
                            <select id="which_column">
                                {% for column in article_columns %}
                                    {% if column == this_article_column.column %}
                                          <option value="{{ column.id }}" selected="selected">{{ column.column }}</option>
                                    {% else %}
                                        <option value="{{ column.id }}">{{ column.column }}</option>
                                    {% endif %}
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <div class="row" style="margin-top: 10px">
                        <div class="col-md-2 text-right"><span>内容：</span></div>
                        <div id="editormd" class="col-md-10 text-left">
                            <textarea style="display: none" id="id_body">{{ article.body }}

                            </textarea>
                        </div>
                    </div>
                    <div class="row" style="margin-top: 10px">
                        <input type="button" class="btn btn-primary btn-lg" value="发布" onclick="redit_article()">
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}